GET http://127.0.0.1:3000/user-api/users

###
POST http://127.0.0.1:3000/user-api/users
Content-Type: application/json

{
    "id":200,
    "name":"dhanvi",
    "age":20
}

###
PUT http://127.0.0.1:3000/user-api/users/200
Content-Type: application/json

{
    "id":200,
    "name":"dhanvi shah",
    "age":21
}
###
DELETE http://127.0.0.1:3000/user-api/users/200

### read user by id
GET http://127.0.0.1:3000/user-api/users/200

###
DELETE http://127.0.0.1:3000/user-api/users/200

### product api
GET http://127.0.0.1:3000/product-api/products

###
GET http://127.0.0.1:3000/product-api/products-id/1

###
GET http://127.0.0.1:3000/product-api/products-brand/colgate

###
POST http://127.0.0.1:3000/product-api/products
Content-Type: application/json

{
    "id":1,
    "name":"tooth-paste",
    "price":30,
    "brand":"colgate"
}

###
PUT http://127.0.0.1:3000/product-api/products/1
Content-Type: application/json

{
    "id":1,
    "name":"tooth-paste",
    "price":40,
    "brand":"patanjai"
}

###
DELETE http://127.0.0.1:3000/product-api/products/1